// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
namespace WEBDemo
{
	using System;
	using System.Web;
	using System.Web.UI;

	public partial class Default
	{
		
		protected System.Web.UI.WebControls.Button button1;
	}
}

